name: foodshedPoetry_2
dependencies:
  - python>=3.7
  - matplotlib>=3.1.0
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - pydantic>=1.4
  - requests>=2.20.1
  - cached-property>=1.5.1
  - typer>=0.3.0
  - httpx>=0.16.1
  - appdirs>=1.4.4
  - pytest>=4.3.1
  - black=19.10b0
  - isort=4.3.21
  - mypy=0.782
  - pylint=2.6.0
  - pip:
    - git+https://github.com/microsoft/task_oriented_dialogue_as_dataflow_synthesis.git} 
    - datasets==1.1.3
    - transformers=4.5.0
    - blobfile>=1.2.5
    - more_itertools>=8.2.0
    - lark-parser>=0.8.2
    - jsons>=0.10.1
